### ISSUE TITLE
Fails to build on Fedora

### ISSUE THREAD

**Issue by honza** [tomassedovic/dose-response#2]
`cargo build --release` fails on Fedora with:

```
./target/release/dose-response: error while loading shared libraries: libtcod.so: cannot open shared object file: No such file or directory
```

This is with tcod dependencies installed.

**Comment by tomassedovic** [comment]
Can you make sure you've got the latest from the `master` branch? I've changed the default branch recently and the code should no longer link to libtcod at all.

**Comment by honza** [comment]
Ah, perfect, I was on the default branch. Works great!

**Comment by tomassedovic** [comment]
Oh but the error message looks like the build succeeded but you tried to run it directly afterwards?

`cargo run` should work. Alternatively, find `libtcod.so` under `target` and run:

    LD_LIBRARY_PATH=target/release/build/tcod-sys-74146fc57fcc4a1f/out/ target/release/dose-response

(substituting to the right `out` directory -- it should contain `libtcod.so`)

Rust doesn't set rpath, so unless the dynamic dependency (e.g. libtcod.so) is installed on your system, you have to specify the path to it. Running `cargo run` sets the environment correctly.

But this is one of the reasons why I've recently moved away from libtcod :-).
